executable    = RunAtBatch.sh
universe      = vanilla
output        = BatchLog/Nano.$(SAMPLE).$(ClusterId).$(ProcId).out
error         = BatchLog/Nano.$(SAMPLE).$(ClusterId).$(ProcId).err
log           = BatchLog/Nano.$(ClusterId).log
stream_output = True
stream_error  = True

#getenv = true
environment = "HOME=$ENV(HOME) JOBWORKDIR=$ENV(PWD)"

+JobFlavour = "microcentury"
arguments = $(SAMPLE)
queue SAMPLE from ( 
#Data22B_DoubleMuon
Data22C_Muon
Data22D_Muon
Data22D_JetMET
)

+JobFlavour = "microcentury"
arguments = $(SAMPLE)
queue SAMPLE from ( 
MC22_122_TTTo2L2Nu
MC22_122_DYJetsToLL
MC22_122_QCD_Pt-15to7000_Flat
)
